version: "3.7"
services:
  web:
    build: ./php
    ports:
      - 8200:80
    volumes:
      - ./shop:/var/www/html

  db:
    build: ./mysql
    volumes:
      - db-storage:/var/lib/mysql

volumes:
  db-storage:
